ecommerce_project/ecommerce_project/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns = [
    # other URL patterns
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')

]

ecommerce_project/ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce_project/ecommerce_project/search_app/urls.py
app_name = "search_app"

from django.urls import path
from search_app import views

urlpatterns = [
    # other URL patterns
    path('search/', views.SearchResult, name='search_result'),
]

ecommerce_project/ecommerce_project/shop_app/urls.py
app_name="shop_app"
from . import views
from django.urls import path

urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodcatedetail')
]

ecommerce_project/ecommerce_project/cart/models.py
from django.db import models
from shop_app.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/ecommerce_project/shop_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop_app:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop_app:prodcatedetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural= 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/ecommerce_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_project/ecommerce_project/search_app/views.py
from django.shortcuts import render
from shop_app.models import Product
from django.db.models import Q

def SearchResult(request):
    query = request.GET.get('q')
    products = Product.objects.none()  # Create an empty queryset initially

    if query:
        products = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    context = {'query': query, 'products': products}
    return render(request, 'search.html', context)

ecommerce_project/ecommerce_project/shop_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.


def allProdCat(request, c_slug=None):
    c_page = None
    products = None

    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce_project/ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>


    <meta name="description" content="{% block metadescription %}{% endblock %} %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>


        {% include 'footer.html' %}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

ecommerce_project/ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    THIS IS THE CART PAGE
{% endblock %}

{% block title %}
   CART
{% endblock %}

{% block content %}

  {% if not cart_items %}
    <div>
      <div class="text-center"><br>
        <h1 class="text-center my_title">
          YOUR SHOPING CART IS EMPTY
        </h1><br>
        <p class="text-center">
          PLEASE CLICK<a href="{% url 'shop_app:allProdCat' %}">HERE</a> TO CONTINUE SHOPPING
       </p>

      </div>
    </div>
  {% else %}
    <div>
      <div class="text-center">
        <br>
        <h1 class="text-center my_title">
          YOUR SHOPPING CART
        </h1>
      </div>
    </div>

<div class="row mx-auto">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
      <thead class="my_custom_thead">
      <tr>
        <th colspan="5">
          YOUR ITEMS
        </th>
      </tr>
      </thead>
      <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <td>
            <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="image" style="width:100px; height:100px;"></a>
          </td>
          <td class="text-lef">
            {{cart_item.product.name}}
            <br>
            SKU: {{cart_item.product.id}}
            <br>
            Price: $ {{cart_item.product.price}}
            <br>
            Qty: {{cart_item.quantity}} x $ {{cart_item.product.price}}

          </td>
          <td>
            $ {{cart_item.sub_total}}
          </td>
          {% if cart_item.quantity < cart_item.product.stock %}
          <td>
            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
</svg></a>&nbsp;
            <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8Z"/>
</svg></a>&nbsp;
            <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
</svg></a>
          </td>
          {% else %}
          <td>
          &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8Z"/>
</svg></a>&nbsp;
            <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
</svg></a>
          </td>
        </tr>
      {% endif %}
         {% endfor %}
      </tbody>

    </table>

  </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
          <tr>
            <th>
              CHECKOUT
            </th>
          </tr>

        </thead>
        <tbody>
          <tr>
            <td>
              PLEASE REVIEW YOUR CART BEFORE PROCEEDING TO PAYMENT
            </td>
          </tr>
        <tr>
          <td class="text-left">
                TOTAL: <strong>{{ total }}</strong>
          </td>
        </tr>

        </tbody>

      </table>
      <div class="mx-auto">
        <a href="{% url 'shop_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>

      </div>
    </div>



</div>

{% endif %}
{% endblock %}

ecommerce_project/ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:1555}}
    {% else %}
        WELCOME TO DIGIKART
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}
    {% else %}
        SEE OUR NEW COLLECTIONS
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row cat_row">
            <div class="mx-auto">
            <p>
                <a href="{% url 'shop_app:allProdCat' %}">OUR PRODUCT COLLECTION</a>
            </p>
        </div></div>
    </div>
{% endif %}
    <div class="mx-auto">
        {% if category %}
            <img class="my_img" src="{{category.image.url}}" alt="{{category.name}}">
    </div><br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.desc}}</p>
    </div>
{% else %}
    <div class="container">
        <img class="my_img img_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1456px" height="500px">
    </div><br>
    <div class="container">
        <h6 class="text-center my_title">our products collection</h6>
        <p class="text-justify">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

    </div>
{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
    <div class="bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
        <div class="card text-center" style="min-width:18rem; height:100%;">

                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a><br><br>
                <div class="card-body">
                <h4>{{product.name}}</h4>
                <br><p>{{product.price}}</p>
                </div>
         </div>
    </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}" href="?page={{pg}}">{{pg}}</a>
            {% endfor %}
        </div>
    {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce_project/ecommerce_project/templates/footer.html
 <div class="my_footer">


  <p class="text-center">&copy;DigiKart pvt all rights reserved</p>
</div>

ecommerce_project/ecommerce_project/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop_app:allProdCat' %}">
    <img src="{% static 'img/logo.png' %}" alt="logimage" width="200" height="200">
    </a>
  </center>
</header>

ecommerce_project/ecommerce_project/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">DigiKart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
            <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
          </svg>
          <span class="sr-only">(current)</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop_app:allProdCat' %}">All Products</a>
          {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
          ({{item_count}})
        </a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:search_result' %}" method="GET">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

ecommerce_project/ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}}
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
<div class="row prod_row">
  <div class="mx_auto">
    <P>
      <a class="btn btn-secondary" href="{% url 'shop_app:allProdCat' %}">Home</a>|<a class="btn btn-secondary" href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}
    </P>
  </div>
</div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
        <div class="text-center">
            <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>
        </div>
            <div class="col-md-6">
            <h1 class="prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p>PRODUCT DESCRIPTION</p>
            <p class="text-justify prod_desc">{{product.desc}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify"><b>OUT OF STOCK</b></p>
            {% else %}
                <div class="pb-5">
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a><br>
            {% endif %}
                    </div>
        </div>
            </div>
        </div>

{% endblock %}

ecommerce_project/ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div>
    <p class="text-center my_search">YOU HAVE SEARCHED FOR <b>{{ query }}</b></p>
  </div>

  <div class="container">
    <div class="row mx-auto">
      {% if products %}
        {% for product in products %}
          <div class="bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width: 18rem; height: 100%;">
              <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a><br><br>
              <div class="card-body">
                <h4>{{ product.name }}</h4>
                <p>{{ product.price }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="row mx-auto">
          <p class="text-center my_search">NO RESULTS FOUND</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}